name:                absolute-time-reader
version:             0.1.0.0
github:              "oscar-h64/absolute-time-reader"
license:             BSD3
author:              "Oscar Harris"
maintainer:          "oscar@oscar-h.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oscar-h64/absolute-time-reader#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  absolute-time-reader-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - absolute-time-reader

tests:
  absolute-time-reader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - absolute-time-reader
